version: '3.8'
services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached      
    network_mode: service:minio
    command: sleep infinity
    environment:
      AWS_ACCESS_KEY_ID: ocfltest
      AWS_SECRET_ACCESS_KEY: ocfltest
      AWS_REGION: us-east-1
      OCFL_TEST_S3: "http://minio:9000"

  minio:
    image: quay.io/minio/minio:RELEASE.2024-09-22T00-33-43Z
    restart: unless-stopped
    volumes:
      - minio-data:/data
    command: server /data
    environment:
      MINIO_ROOT_USER: ocfltest
      MINIO_ROOT_PASSWORD: ocfltest

volumes:
  minio-data:
